### ISSUE TITLE
encrypted snapshots

### ISSUE THREAD

**Issue by ethanwinograd** [upmc-enterprises/elasticsearch-cron#1]
is it possible to make this cron job write the snapshots out in an encrypted manner to s3?

ie. $ aws s3 cp text.txt s3://test-bucket --sse

**Comment by stevesloka** [comment]
Looks like when the repository is created, need to set the `server_side_encryption` flag (https://www.elastic.co/guide/en/elasticsearch/plugins/current/repository-s3-repository.html).

The update would go here: https://github.com/upmc-enterprises/elasticsearch-cron/blob/master/main.go#L57

**Comment by ethanwinograd** [comment]
for the change to be picked up we will need to deploy to docker hub and rebuild the operator with a pointer to the updated module,  is that correct?

https://github.com/upmc-enterprises/elasticsearch-operator/blob/master/pkg/snapshot/scheduler.go#L41
